# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
